class QuitTestSystem(Exception): ...

class FailedTest(Exception): ...

class SkippedTest(Exception): ...

class AbortTestSequence(Exception):
    """raised by test_step to indicate the termination of the test sequence"""
